#!/bin/bash

# location of the JAVA command to use
JAVAC=/usr/lib/jvm/java-8-oracle/bin/javac

# location of additional JAVA libraries to use
JAVALIB=/home/pilou/Software/Mipav/jre/lib/ext/

# location of the MIPAV installation to use
MIPAV=/home/pilou/Software/Mipav-8.0.2

# location of the JIST installation to use
JIST=/home/pilou/Software/JIST_CRUISE-bundle-for-CBSToolsR1

# location of the plugin installation to use
# please replace 'ThisUser' by your user name
PLUGINS=/home/pilou/mipav/plugins

# location of the code
CBSTOOLS=/home/pilou/Code/github/cbstools-public
IMCN=/home/pilou/Code/github/imcn-imaging

# mipav command
echo "compile $@ ..."
#$JAVAC -classpath $CBSTOOLS:$JAVALIB/*:$MIPAV:$MIPAV/lib/*:$JIST:$JIST/library/*:$PLUGINS:$/library/* -server -g -O -deprecation -encoding UTF-8 $@
$JAVAC -classpath $IMCN:$IMCN/lib/* -server -g -O -deprecation -encoding UTF-8 $@

